import type { ReactNode } from "react";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Apple, DollarSign, Gauge, Leaf, Plane, type LucideIcon } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { MetricTile } from "@/components/common/MetricTile";
import { SectionCard } from "@/components/common/SectionCard";
import { SectionSkeleton } from "@/components/common/SectionSkeleton";
import { BackendErrorCard } from "@/components/common/BackendErrorCard";
import { useRegion } from "@/contexts/RegionContext";
import { useImpactOverview } from "@/hooks/useHarvestFlow";
import { chartAxis, chartColors, chartGrid, chartTooltip } from "@/utils/charts";
import type { ImpactMetric, SeriesPoint } from "@/types";

const impactIcons: Record<ImpactMetric["icon"], LucideIcon> = {
  food: Apple,
  revenue: DollarSign,
  carbon: Leaf,
  efficiency: Gauge,
  export: Plane,
};

export function Impact() {
  const { data, isLoading, isError, refetch } = useImpactOverview();
  const { selectedRegion } = useRegion();
  const regionSummary = selectedRegion === "All Regions" ? "National" : selectedRegion;

  return (
    <div className="space-y-8">
      <PageHeader
        title="Impact Overview"
        subtitle={`Executive summary of operational and export impact for ${regionSummary} generated by HarvestFlow AI.`}
      />

      {isLoading ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {Array.from({ length: 4 }).map((_, i) => (
            <SectionSkeleton key={i} />
          ))}
        </div>
      ) : isError || !data ? (
        <BackendErrorCard onRetry={() => void refetch()} />
      ) : (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
            {data.metrics.map((m) => (
              <MetricTile
                key={m.key}
                icon={impactIcons[m.icon]}
                label={m.label}
                value={m.value}
                sub={selectedRegion === "All Regions" ? m.sub : `${m.sub} • ${selectedRegion}`}
                tone={m.tone}
              />
            ))}
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <ChartCard title="Spoilage Reduction" subtitle="Before vs after HarvestFlow AI (%)">
              <SpoilageChart data={data.spoilage} />
            </ChartCard>
            <ChartCard title="Revenue Improvement" subtitle="Monthly Export Revenue Protected">
              <RevenueChart data={data.revenue} />
            </ChartCard>
            <ChartCard title="Storage Utilization" subtitle="Average % across regional facilities">
              <StorageUtilChart data={data.storage} />
            </ChartCard>
            <ChartCard title="Carbon Savings" subtitle="Cumulative tons CO₂e prevented">
              <CarbonChart data={data.carbon} />
            </ChartCard>
          </div>
        </>
      )}
    </div>
  );
}

function ChartCard({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return (
    <SectionCard title={title} subtitle={subtitle}>
      <div className="h-64">{children}</div>
    </SectionCard>
  );
}

function SpoilageChart({ data }: { data: SeriesPoint[] }) {
  return (
    <ResponsiveContainer width="100%" height="100%">
      <BarChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={chartGrid} />
        <XAxis dataKey="month" tick={chartAxis} tickLine={false} axisLine={false} />
        <YAxis tick={chartAxis} tickLine={false} axisLine={false} />
        <Tooltip contentStyle={chartTooltip} />
        <Legend wrapperStyle={{ fontSize: 11 }} />
        <Bar dataKey="before" fill={chartColors.critical} radius={[4, 4, 0, 0]} name="Before" />
        <Bar dataKey="after" fill={chartColors.primary} radius={[4, 4, 0, 0]} name="After" />
      </BarChart>
    </ResponsiveContainer>
  );
}

function RevenueChart({ data }: { data: SeriesPoint[] }) {
  return (
    <ResponsiveContainer width="100%" height="100%">
      <LineChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={chartGrid} />
        <XAxis dataKey="month" tick={chartAxis} tickLine={false} axisLine={false} />
        <YAxis tick={chartAxis} tickLine={false} axisLine={false} />
        <Tooltip contentStyle={chartTooltip} />
        <Line type="monotone" dataKey="value" stroke={chartColors.ai} strokeWidth={2.5} dot={{ r: 3 }} />
      </LineChart>
    </ResponsiveContainer>
  );
}

function StorageUtilChart({ data }: { data: SeriesPoint[] }) {
  return (
    <ResponsiveContainer width="100%" height="100%">
      <AreaChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
        <defs>
          <linearGradient id="imp-util" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={chartColors.ai} stopOpacity={0.4} />
            <stop offset="100%" stopColor={chartColors.ai} stopOpacity={0} />
          </linearGradient>
        </defs>
        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={chartGrid} />
        <XAxis dataKey="month" tick={chartAxis} tickLine={false} axisLine={false} />
        <YAxis tick={chartAxis} tickLine={false} axisLine={false} domain={[40, 90]} />
        <Tooltip contentStyle={chartTooltip} />
        <Area type="monotone" dataKey="util" stroke={chartColors.ai} strokeWidth={2} fill="url(#imp-util)" />
      </AreaChart>
    </ResponsiveContainer>
  );
}

function CarbonChart({ data }: { data: SeriesPoint[] }) {
  return (
    <ResponsiveContainer width="100%" height="100%">
      <BarChart data={data} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={chartGrid} />
        <XAxis dataKey="month" tick={chartAxis} tickLine={false} axisLine={false} />
        <YAxis tick={chartAxis} tickLine={false} axisLine={false} />
        <Tooltip contentStyle={chartTooltip} />
        <Bar dataKey="tons" fill={chartColors.primary} radius={[4, 4, 0, 0]} />
      </BarChart>
    </ResponsiveContainer>
  );
}
